[package]
name = "cancer_migration_sims"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
ndarray = "0.17.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
petgraph = "0.6"
clap = { version = "4.5.58", features = ["derive"] }
